sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
    - $HOME/.m2/repository
addons:
  apt:
    packages:
      - rpm
before_install:
  # Use GCE Docker mirror: https://cloud.google.com/container-registry/docs/using-dockerhub-mirroring
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"' | sudo tee -a /etc/default/docker > /dev/null
  - sudo service docker restart
  - docker system info
script:
  - mvn verify -B
before_deploy:
  - find . -type f -name 'original-*.jar' -delete
  - mvn jdeb:jdeb
  - mvn rpm:rpm
deploy:
  provider: releases
  api_key:
    secure: "I1kEu8TuMViRIs3r7CJMxdg9MvX6NGBjub57ZgojvBtscHbsHXguB3mM9Zngl2qyw+Hjyd//Djrh5x+rEMUs7cdMF8ITI+zwLUW27Tu3WHwi3cGEjcodPKdaboEpCue/p5cVtuyV5mXpeY0WMb0QkLtIotp6wWUS5NMLI1RN3YQ="
  file_glob: true
  file:
    - "**/target/*.jar"
    - "**/target/*.deb"
    - "**/target/**/*.rpm"
  skip_cleanup: true
  on:
    tags: true
